### ISSUE TITLE
Roblox has built in type checking making this kinda useless

### ISSUE THREAD

**Issue by walksanatora** [osyrisrblx/t#105]
as defined in the luau documentation the languague actually has built in type checking (https://luau-lang.org/typecheck)[https://luau-lang.org/typecheck]

**Comment by walksanatora** [comment]
so your example could be written in plain luau as
```lua
local function foo(a:string, b:number, c:string|nil)
	assert(fooCheck(a, b, c))
	-- you can now assume:
	--	a is a string
	--	b is a number
	--	c is either a string or nil
end

foo() <-- script errors with a type error at parse phase
foo("1", 2)
foo("1", 2, "3")
foo("1", 2, 3) <--also a error during parse
```

**Comment by OverHash** [comment]
Right, but that doesn't help with functions that are ran with unknown data. E.g., remote events. A large portion of [roblox-ts](https://roblox-ts.com/) users use `t`, and they've had typechecking for years.

**Comment by osyrisrblx** [comment]
OverHash is correct.

You can think of `t` as a supercharged `typeof(X) == "Y"`. It's useful for:
- Typechecking unknown data like RemoteEvent responses, decoded JSON, etc.
- Discriminating union types like `Foo | Bar`
