### ISSUE TITLE
t.instanceIsA conflicts with documentation

### ISSUE THREAD

**Issue by RuizuKun-Dev** [osyrisrblx/t#91]
In code:
![image](https://user-images.githubusercontent.com/55673217/110122867-c6744b80-7df2-11eb-93ae-aba2bad3a1d0.png)

In Documentation:
![image](https://user-images.githubusercontent.com/55673217/110122908-d429d100-7df2-11eb-9251-ec5c157b9a82.png)

**Comment by osyrisrblx** [comment]
`t.instanceIsA()` works like this:

`t.instanceIsA("Player")(player)`
